apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cordova-plugin-ionic-webview2
  annotations:
    github.com/project-slug: lampo/cordova-plugin-ionic-webview2
spec:
  type: general
  lifecycle: production
